### ISSUE TITLE
support tcp keepalives

### ISSUE THREAD

**Issue by nathanhruby** [crowdin/crowdin-cli-2#18]
(this is repost of crowdin/crowdin-cli#58 where we discovered this issue.  That code doesn't seem to be supported so reopening here as requested since this codebase doesn't seem to support keepalives as far as I can tell)

When trying to download a large project that creates a new export, a request can take a long time (in the case that I am seeing ~60 minutes). When this happens, the cli client keeps the connection open and expects it to remain intact while idle.

This doesn't work behind a lot of firewalls or NAT gateways that have idle connection time limits (AWS NAT Gateway specifically has a 5 min limit and is the one that triggered this issue for us). When this happens and the connection is drop'ed in the middle without a corresponding RST being sent (which is a separate kind of wrong) the client thinks the connection is still up and waits patiently forever to hear back from the remote.

Please support TCP keepalives for http connections in order to avoid this issue. When inspecting the TCP socket the keepalive flag is not added. For the short term we were able to work around the issue with https://github.com/flonatel/libdontdie

**Comment by ihor-popyk** [comment]
We will think about implemented this thing in our future releases.
Thank you very much for your suggestion.

**Comment by andrii-bodnar** [comment]
Hi @nathanhruby !
In [CLI 3](https://github.com/crowdin/crowdin-cli-2/tree/cli3#readme) download command is asynchronous and there are no long-time exports anymore. Try to use this version.
