### ISSUE TITLE
Uploading files with the new CLI tool ignores "dest" parameter

### ISSUE THREAD

**Issue by d4rken** [crowdin/crowdin-cli-2#25]
Using the old tool on another computer it uploads files correctly to subfolders, while the new tool just puts them in the root folder of my crowdin project.

Old tool:
```
Updating source file `sdmaid/strings.xml' - OK
Updating source file `unlocker/strings.xml' - Skipped
Updating source file `sdmaid/description.txt' - OK
Updating source file `sdmaid/title.txt' - Skipped
Updating source file `sdmaid/short_description.txt' - Skipped
Updating source file `unlocker/description.txt' - Skipped
Updating source file `unlocker/title.txt' - Skipped
Updating source file `unlocker/short_description.txt' - Skipped
```

New tool:
```
File '/strings.xml' - OK
File '/strings.xml' - OK
File '/description.txt' - OK
File '/title.txt' - OK
File '/short_description.txt' - OK
File '/description.txt' - OK
File '/title.txt' - OK
File '/short_description.txt' - OK
```

Config
```
"project_identifier" : "sdmaid"

"files" : [
  {
    "source" : "/sdmaid/src/main/res/values/strings.xml",
    "dest" : "/sdmaid/strings.xml",
    "translation" : "/sdmaid/src/main/res/values-%android_code%/%original_file_name%",
#    "update_option" : "update_as_unapproved",
    "languages_mapping" : &stringmapping {
      "android_code" : {
        "ar" : "ar",
        "am" : "am",
        "hy-AM" : "hy-rAM",
        "az" : "az",
        "be" : "be",
        "bn" : "bn-rBD",
        "bg" : "bg",
        "ca" : "ca",
        "cs" : "cs",
        "da" : "da",
        "de" : "de",
        "el" : "el",
        "es-ES" : "es",
        "es-AR" : "es-rAR",
        "es-MX" : "es-rMX",
        "es-VE" : "es-rVE",
        "et" : "et-rEE",
        "eu" : "eu-rES",
        "fa" : "fa",
        "fil" : "fil",
        "fi" : "fi",
        "fr" : "fr",
        "gl" : "gl-rES",
        "hr" : "hr",
        "hu" : "hu",
        "hy-AM" : "hy-rAM",
        "is" : "is",
        "id" : "in",
        "it" : "it",
        "he" : "iw",
        "ja" : "ja",
        "ka" : "ka-rGE",
        "km" : "km-rKH",
        "kn" : "kn-rIN",
        "ko" : "ko",
        "ky" : "ky-rKG",
        "lt" : "lt",
        "lv" : "lv",
        "lo" : "lo-rLA",
        "ms" : "ms",
        "ml-IN" : "ml-rIN",
        "mn" : "mn-rMN",
        "mr" : "mr-rIN",
        "my" : "my-rMM",
        "ne-NP" : "ne-rNP",
        "nl" : "nl",
        "no" : "no",
        "pl" : "pl",
        "pt-PT" : "pt",
        "pt-BR" : "pt-rBR",
        "ro" : "ro",
        "ru" : "ru",
        "rm-CH" : "rm",
        "si-LK" : "si-rLK",
        "sk" : "sk",
        "sl" : "sl",
        "sr" : "sr",
        "sv-SE" : "sv",
        "sw" : "sw",
        "th" : "th",
        "ta" : "ta-rIN",
        "te" : "te-rIN",
        "tr" : "tr",
        "uk" : "uk",
        "ur-IN" : "ur-rIN",
        "uz" : "uz",
        "vi" : "vi",
        "zh-CN" : "zh-rCN",
        "zh-HK" : "zh-rHK",
        "zh-TW" : "zh-rTW",
        "zu" : "zu"
      }
    }
  }, {
    "source" : "/unlocker/src/main/res/values/strings.xml",
    "dest" : "/unlocker/strings.xml",
    "translation" : "/unlocker/src/main/res/values-%android_code%/%original_file_name%",
#    "update_option" : "update_without_changes",
    "languages_mapping" : *stringmapping
  }, {
    "source" : "/sdmaid/fastlane/metadata/android/en-US/full_description.txt",
    "dest" : "/sdmaid/description.txt",
    "translation" : "/sdmaid/fastlane/metadata/android/%locale%/full_description.txt",
#    "update_option" : "update_without_changes",
    "languages_mapping" : &playstoremapping {
      "locale" : {
        "af" : "af",
        "ar" : "ar",
        "am" : "am",
        "hy-AM" : "hy-AM",
        "az" : "az-AZ",
        "be" : "be",
        "bn" : "bn-BD",
        "bg" : "bg",
        "ca" : "ca",
        "cs" : "cs-CZ",
        "da" : "da-DK",
        "de" : "de-DE",
        "el" : "el-GR",
        "es-ES" : "es-ES",
        "es-AR" : "es-AR",
        "es-MX" : "es-419",
        "es-VE" : "es-VE",
        "et" : "et",
        "eu" : "eu-ES",
        "fa" : "fa",
        "fil" : "fil",
        "fi" : "fi-FI",
        "fr" : "fr-FR",
        "fr-CA" : "fr-CA",
        "gl" : "gl-ES",
        "hr" : "hr",
        "hu" : "hu-HU",
        "hy-AM" : "hy-AM",
        "is" : "is-IS",
        "id" : "id",
        "it" : "it-IT",
        "he" : "iw-IL",
        "hi" : "hi-IN",
        "ja" : "ja-JP",
        "ka" : "ka-GE",
        "km" : "km-KH",
        "kn" : "kn-IN",
        "ko" : "ko-KR",
        "ky" : "ky-KG",
        "lt" : "lt",
        "lv" : "lv",
        "lo" : "lo-LA",
        "mk" : "mk-MK",
        "ms" : "ms",
        "ml-IN" : "ml-IN",
        "mn" : "mn-MN",
        "mr" : "mr-IN",
        "my" : "my-MM",
        "ne-NP" : "ne-NP",
        "nl" : "nl-NL",
        "no" : "no-NO",
        "pl" : "pl-PL",
        "pt-PT" : "pt-PT",
        "pt-BR" : "pt-BR",
        "ro" : "ro",
        "ru" : "ru-RU",
        "rm-CH" : "rm",
        "si-LK" : "si-LK",
        "sk" : "sk",
        "sl" : "sl",
        "sr" : "sr",
        "sv-SE" : "sv-SE",
        "sw" : "sw",
        "th" : "th",
        "ta" : "ta-IN",
        "te" : "te-IN",
        "tr" : "tr-TR",
        "uk" : "uk",
        "ur-IN" : "ur-IN",
        "uz" : "uz",
        "vi" : "vi",
        "zh-CN" : "zh-CN",
        "zh-HK" : "zh-HK",
        "zh-TW" : "zh-TW",
        "zu" : "zu"
      }
    }
  }, {
     "source" : "/sdmaid/fastlane/metadata/android/en-US/title.txt",
     "dest" : "/sdmaid/title.txt",
     "translation" : "/sdmaid/fastlane/metadata/android/%locale%/title.txt",
#    "update_option" : "update_without_changes",
     "languages_mapping" : *playstoremapping
  }, {
     "source" : "/sdmaid/fastlane/metadata/android/en-US/short_description.txt",
     "dest" : "/sdmaid/short_description.txt",
     "translation" : "/sdmaid/fastlane/metadata/android/%locale%/short_description.txt",
#    "update_option" : "update_without_changes",
     "languages_mapping" : *playstoremapping
  }, {
     "source" : "/unlocker/fastlane/metadata/android/en-US/full_description.txt",
     "dest" : "/unlocker/description.txt",
     "translation" : "/unlocker/fastlane/metadata/android/%locale%/full_description.txt",
#    "update_option" : "update_without_changes",
     "languages_mapping" : *playstoremapping
  }, {
     "source" : "/unlocker/fastlane/metadata/android/en-US/title.txt",
     "dest" : "/unlocker/title.txt",
     "translation" : "/unlocker/fastlane/metadata/android/%locale%/title.txt",
#    "update_option" : "update_without_changes",
     "languages_mapping" : *playstoremapping
  }, {
     "source" : "/unlocker/fastlane/metadata/android/en-US/short_description.txt",
     "dest" : "/unlocker/short_description.txt",
     "translation" : "/unlocker/fastlane/metadata/android/%locale%/short_description.txt",
#    "update_option" : "update_without_changes",
     "languages_mapping" : *playstoremapping
  }
]
```

**Comment by d4rken** [comment]
Bug was likely introduced here https://github.com/crowdin/crowdin-cli-2/commit/d3570b65972257781f5d36519a4b9f3575ab4453#diff-c2cad281f60ff212b073aa518b0b75c4R441

**Comment by d4rken** [comment]
Fix idea https://github.com/crowdin/crowdin-cli-2/pull/26

Unconfirmed though so someone from crowdin should still check that.

**Comment by ihor-popyk** [comment]
Hello, @d4rken 
First of all, sorry for so long delay.
I was considering your example, and can tell you, if you need to keep folders (in your case `unlocker` and `sdmaid`) in Crowdin you must set parameter `preserve_hierarchy` to `true` (default false).
Please, try it in our the newest version of CLI. Hope, it helps you.

**Comment by d4rken** [comment]
I originally tried the parameter `preserve_hierarchy`  already, but it had no effect, likely because I specified the `dest` parameter. The [configuration documentation states ](https://support.crowdin.com/configuration-file/) that you:

* by default get all files sans their common base pathes but still individual folders (i.e. uncommon base pathes)
* or you specify the `preserve_hierarchy` parameter, so the tool recreates the local file structure exactly
* or you specify the structure explicitly with `dest`.

So your recommendation to fix this with the `preserve_hierarchy` flag seems wrong here. Furthermore, seeing as the previous CLI tool just works and crowdin states in multiple places that the previous configuration files are compatible with the new CLI tool, if `preserve_hierarchy` would be necessary and is by default `false` then wouldn't this also be a bug?

Anyways, I tested the new CLI tool version (`2.0.12`) with `preserve_hierarchy` for you and it still doesn't work, which would be correct as `preserve_hierarchy` is not the solution to this and because when `dest` is specified `preserve_hierarchy` should have no effects (otherwise undefined behavior).

Why is the solution attempt in #26 not the correct approach? I actually tested it and it seems to work fine, I'm just not sure about side effects from other parameters.

CLI v2.0.12 with `preserve_hierarchy  (+my config above):

![with_preserve_hierarchy](https://cloud.githubusercontent.com/assets/1439229/23946930/c4929cca-097c-11e7-84a4-141bd97dc687.PNG)

CLI v2.0.12 without `preserve_hierarchy` (+my config above):

![without_preserve_hierarchy](https://cloud.githubusercontent.com/assets/1439229/23946937/c81576ec-097c-11e7-89d7-23713323fab7.PNG)

#25 with `preserve_hierarchy`  (+my config above):

![with_fix](https://cloud.githubusercontent.com/assets/1439229/23946914/b3ff9bce-097c-11e7-9124-73158fd1e9a9.PNG)

#25 without `preserve_hierarchy` (+my config above):

![with_fix_without_preserve_hierarchy](https://cloud.githubusercontent.com/assets/1439229/23946923/ba025a98-097c-11e7-9256-b2d3a1a2b800.PNG)


I mean just look at the code (original code, still in place in `2.0.12`):

```
File sourceFile = new File(source);
                Boolean isDest = file.getDest() != null && !file.getDest().isEmpty() && !this.commandUtils.isSourceContainsPattern(file.getSource());
                String preservePath = file.getDest();
                preservePath = this.commandUtils.preserveHierarchy(file, sourceFile.getAbsolutePath(), commonPath, this.propertiesBean, this.branch, this.credentials, this.isVerbose);
                String fName;
                if (isDest) {
                    fName = new File(file.getDest()).getName();
                } else {
                    fName = sourceFile.getName();
                }
                preservePath = preservePath + PATH_SEPARATOR + fName;
                preservePath = preservePath.replaceAll(PATH_SEPARATOR + "+", PATH_SEPARATOR);
                if (preservePath.startsWith(PATH_SEPARATOR)) {
                    preservePath = preservePath.replaceFirst(PATH_SEPARATOR, "");
                }
```

* `file.getDest()` is used to determine if the the parameter is set i.e. `isDest` is set, ok.
* Then we take the path with `preservePath = file.getDest()`, also ok.
* Then we overwrite in `perserve = this.commandUtils...` and path specified in `dest` is lost.
* We check `isDest` then again to get the file name, but the path is just ignored.

**Comment by ihor-popyk** [comment]
Now option `preserve_hierarchy` affect everywhere, and in `dest` path also. We improved this in new CLI. We believe it will be more clearly. Hope, it's not big problem for you. 
And I finally found one more bug when using CLI on Windows OS. Please, just try last changes from `develpment` branch, and hope it will work for you (also use `preserve_hierarchy=true`)

**Comment by ihor-popyk** [comment]
Your solution is good in your case, but, unfortunately, has some bad effects on the other side.

**Comment by d4rken** [comment]
Now it works 👍 . I still don't understand why `preserve_hierarchy` is necessary when specifying `dest`.

Please check https://support.crowdin.com/configuration-file/#saving-directory-structure-on-server it and https://support.crowdin.com/configuration-file/#uploading-files-to-specified-path-with-specified-type

It's just not clear (at least to me) why preserve_hierarchy is required. Especially because documentation makes it seem that `dest` allows specifying a file path and that example doesn't have `preserve_hierarchy` either.
From the documentation I would thought that `preserve_hierarchy` affects the path only when multiple files have the same common parent folders, which are then omitted for a cleaner structure and this wouldn't affect my case. 

```
    "source" : "/sdmaid/src/main/res/values/strings.xml",
    "dest" : "/sdmaid/strings.xml",
```
```
    "source" : "/unlocker/src/main/res/values/strings.xml",
    "dest" : "/unlocker/strings.xml",
```
don't share a common directory. But if this really is the desired behavior for for `dest` and `preserve_hierarchy` then CLI tool should abort the upload process if it detects that multiple files from the same upload will overwrite each other, as this is very likely with the way it currently behaves.

I would propose to add a check for files from the same upload overwritting each other and to make `dest` work independent of `preserve_hierarchy`. Meaning if `dest` is set, then `preserve_hierarchy` is automatically set to true. At least I don't see a case which requires dest to be set but `preserve_hierarchy` to be false, do you?

It also is weird that it is not skipping all files, because there was nothing changed in them. But it's likely not related to this bug. Maybe some windows/linux/mac \n\t\r issue? Are normalizing the input, i.e. like in git?
```
Connected to the target VM, address: '127.0.0.1:60244', transport: 'socket'
File 'sdmaid/strings.xml'-
 - SKIPPED
File 'unlocker/strings.xml' - OK
File 'sdmaid/description.txt' - OK
File 'sdmaid/title.txt'\
 - SKIPPED
File 'sdmaid/short_description.txt' - SKIPPED
File 'unlocker/description.txt' - OK
File 'unlocker/title.txt' - SKIPPED
File 'unlocker/short_description.txt' - SKIPPED
Disconnected from the target VM, address: '127.0.0.1:60244', transport: 'socket'
```

**Comment by d4rken** [comment]
I envision it like this

* Case1, No preserve, no dest. Crowdin optimizes the pathes on their server. 
* Case2, Preserve=true, no dest. Crowdin replicates the local path on their server.
* Case3a, Preserve=true, dest set. Crowdin uses the path from `dest` on their server.
* Case3b, Preserve=false, dest set. Crowdin uses the path from `dest` on their server.

Which would be 3 cases for path handling:
* Automatic (optimized)
* Disabled (preserved)
* Manual (dest)

I think `dest` should override `preserve_hierarchy` this would be less confusing and is then actually the same behavior from CLI 1.0, so the same config files can then be used.

https://github.com/crowdin/crowdin-cli#preserving-directories-hierarchy
https://support.crowdin.com/configuration-file/#saving-directory-structure-on-server
