### ISSUE TITLE
Localising .strings files for iOS

### ISSUE THREAD

**Issue by MattSHallatt** [crowdin/crowdin-cli-2#29]
I've recently started my free trial with Crowdin to see if it would be suitable to use going forward in my iOS apps.
From what I've seen, it seems really useful.
However, I'm having difficulties getting it to work with `.strings` files, which are the kind of files used for localisations in iOS projects.

This is my configuration for source and translations:
```
  "source" : "/AppName/en.lproj/Localizable.strings",

  "translation" : "/AppName/%osx_code%/%original_file_name%",
```

I've tried different formats within the `.strings` file itself.

Ideally I'd like to define my strings in a key-value format:
```
"key" = "value"
```
But neither this or just having a string in or out of quotes works:
```
"String"
-----
String
```

The files upload and download absolutely fine using:
```
crowdin upload sources
-----
crowdin download
```

The issue is, once the file is on the system, it doesn't pick up any strings in the file to be translated.

<img width="1167" alt="screen shot 2017-03-17 at 11 10 59" src="https://cloud.githubusercontent.com/assets/1385419/24040765/741e22e6-0b02-11e7-9981-6bdd6944c8bf.png">

**Comment by ihor-popyk** [comment]
Hello @MattSHallatt 
Kindly note that iOS .strings file has the following structure:

"key_1"="Text for translation #1";
"key_2"="Text for translation #2";
"key_3"="Text for translation #3";
"key_4"="Text for translation #4";
"key_5"="Text for translation #5";

Can you please re-format your file a bit and let us know whether it worked? You can also find detailed documentation here:
https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html

**Comment by MattSHallatt** [comment]
You are entirely correct - it was the missing semicolon that seemed to stop it from working!
Tested now and upload, translation and download worked a treat!
Thanks for your reply and sorry to bug you with a problem that wasn't your fault!

**Comment by ihor-popyk** [comment]
Glad to hear that all is well!
Have a great weekend @MattSHallatt !
