### ISSUE TITLE
"ignore" does not ignore log4j.properties

### ISSUE THREAD

**Issue by trejkaz** [crowdin/crowdin-cli-2#38]
Java uses the same extension for string properties files and for other configuration files, so I would like to ignore all the other properties files.

So I tried to do this:

    files:
    - source: "/**/src/resources/**/*.properties"
      translation: "%original_path%/%file_name%_%two_letters_code%.%file_extension%"
      ignore:
      - "/**/*_*.properties"
      - "/**/build/*"
      - "/**/log4j.properties"
      - "/**/plugin-descriptor.properties"
      - "/**/portable-config.properties"
      type: properties

When I run:

    java -jar ~/downloads/2.0.14/crowdin-cli.jar  list project | grep log4j

It shows two files being included which surely match the ignore pattern:

    /server/src/resources/config/log4j.properties
    /util/src/resources/config/log4j.properties

The other 4 ignore entries work as expected, even though two of them look exactly the same as the log4j.properties ignore. I even scraped for funny Unicode characters, in case something funny was in there, but no, it's all ASCII as far as I can tell, so I don't know why log4j.properties isn't working.

**Comment by ihor-popyk** [comment]
Hello @trejkaz 
Did you upload your source files via CLI using this configuration file?  I tried to recreate your files structure and the configuration file scheme, however, once I ran  `crowdin upload sources --dryrun | grep log4j`  command, no files were displayed.

**Comment by trejkaz** [comment]
Yeah, it was certainly that configuration file doing it. I had also tried removing other ignore entries to make sure it was really using the file, and it did bring other files back in, so it must have been using that file.

Support seemed to think it was somehow related to having uploaded the files previously before adding the filter..? But the odd thing was, running the list command did still list them, and that one shouldn't even be connecting to the server to see what's already there. (Maybe it does, though...)

**Comment by ihor-popyk** [comment]
If you have uploaded these files to Crowdin before having specified ignoring filters, it is obviously that applying `list project` command these files will be mentioned.
Command `list project` connects to Crowdin server and displays a list of files that are already uploaded to your project.
In order to check which files will be uploaded to your project (taking into account the ignoring filters) please use `upload sources --dryrun` command.
Please let me know if everything works as expected.

**Comment by trejkaz** [comment]
OK.

I can confirm that `list project` doesn't list log4j.properties anymore, probably because I deleted everything on the server side at some point.

`upload sources --dryrun` also isn't listing the file. Or at least, now it's not.

Doing a dry run is awfully slow though:

```
$ time java -jar ~/Downloads/2.0.15/crowdin-cli.jar upload sources --dryrun | grep log4j.properties

real	3m10.411s
user	1m17.187s
sys	1m51.149s
```

**Comment by ihor-popyk** [comment]
@trejkaz 
So glad to hear that everything is working as expected.
Thank you for your collaboration!
On the issue of performance, let's resolve in the relevant issue (#39)
