### ISSUE TITLE
Missing -c shorthand

### ISSUE THREAD

**Issue by atomfrede** [crowdin/crowdin-cli-2#42]
When migrating from v1 to new v2 the shorthand option `-c` for configuration is missing if you are used to v1 cli. It would be cool to have either the `-c` shorthand option again or warn the user when an unknown options is passed.

Or is there a specific reason why leaving `-c` out in v2?

I can also try to do a PR.

**Comment by ihor-popyk** [comment]
Hello @atomfrede
Looks like fair comment. So, short option will be returned in next release.
Thanks for advice.

**Comment by atomfrede** [comment]
@ihor-popyk Awesome. If you like a can do a PR.

**Comment by ihor-popyk** [comment]
@atomfrede I will do it.
TX :)

**Comment by ihor-popyk** [comment]
https://github.com/crowdin/crowdin-cli-2/pull/43

**Comment by ihor-popyk** [comment]
Already done.
@atomfrede let me know if everything ok.
These changes will be present in CLI 2.0.15

**Comment by atomfrede** [comment]
Thx! Will try it tomorrow, but it looks good so far.
