### ISSUE TITLE
Translationlinking breaks on upload from different os

### ISSUE THREAD

**Issue by SeameX** [crowdin/crowdin-cli-2#46]
Hello,

we are working in a team  with different operating systems. Depending which os upload our (the same) source files the translation linking breaks. Looks like its only happening on translations with line breaks.

It would be awesome if you can fix that :)

Best regards

Stefan

**Comment by Andrulko** [comment]
Hello @SeameX ,

Can you please provide the configuration file you use? What is the file type you upload? On which OS the upload doesn't work fine?

Any samples of the affected strings would be more than appreciated :)

**Comment by SeameX** [comment]
Sorry for the late response. I was on vacation.

Our config file looks like this:
`"project_identifier" : "ident"
"api_key" : "key"
"base_path" : "src/main"

"preserve_hierarchy": true

"files": [
  {
   source: 'test.hbs',
   translation: 'test-%locale_with_underscore%.hbs'
  }`

The translation File that we are uploading is a  (utf-8 crlf) multiline html template something like this: 
` <html, head, etc.>
Hello {{userName}},
<br/>
<br/>
Your account has been successfully activated.
</html, body etc.>
`
Steps to reproduce:
1. upload sources on windows (sources are crlf)
2. link translations
3. upload sources on linux (sources are cr)

Translation linking is then broken.

**Comment by Andrulko** [comment]
@SeameX The issue is not linked with CLI directly, it's related to .hbs file format parser. Indeed, when lineending is switched from Windows to UNIX, some strings are considered as new, consequently translations are deleted after the update. This is something we are going to improve the nearest time!
