### ISSUE TITLE
ignore seems not to work

### ISSUE THREAD

**Issue by Remolutionary** [crowdin/crowdin-cli-2#56]
I wanted to ignore some files for translation but it seems not to work at all. 

I'm using the crowdin command line tool (2.0.17) with the following crowdin.yml-file (without project_identifier etc.):

```javascript
files: [
 {
  "source" : "\\SDC.Resources\\*.resx",
  "translation" : "\\SDC.Resources\\%file_name%.%two_letters_code%.resx",
  "ignore" : [
    "\\SDC.Resources\\AccountRes.de.resx",
    ],
 },
```
In the SDC.Resources folder are the source-files (*.resx) as well as the translated files which end with *.de.resx. 
I tried many other ignore patterns like
```javascript
"**\\*.de.resx",
"*.de.resx",
"/*.de.resx",
"**/*.de.resx"
```
In the end I tried to explicitly ignore one file but even that seems not work.
I'm using the Windows-style directory separator as suggested in the docs for setting the base_path and the source and I assumed to do that also in the ignore-section. 

Am I doing something wrong or is there something wrong?

**Comment by ihor-popyk** [comment]
#57 
Hello @Remolutionary 
Fixed this bug.
Thanks a lot!

**Comment by Remolutionary** [comment]
Very nice! Thank you for the quick fix!

I'm using the following ignore settings and everything works as expected now.
```javascript
"ignore" : [
    "\\**\\*.[a-z][a-z].resx",
    "\\**\\*.[a-z][a-z]-[A-Z][A-Z].resx",
    ]
```
