### ISSUE TITLE
setup_crowdin.bat should navigate to script path before calling %cd%

### ISSUE THREAD

**Issue by JustArchi** [crowdin/crowdin-cli-2#61]
It's not guaranteed for the script to be started from its own directory. This is even more true when we start script as administrator, as in this case `%cd%` almost always evaluates to `C:\Windows\system32`.

```
@echo off
SETLOCAL
SET TEMPFILE=%TEMP%\tmpfile

setx /M CROWDIN_HOME "%cd%"
setx /M PATH "%PATH%;%cd%"
...
```

Should be:

```
@echo off
SETLOCAL
SET TEMPFILE=%TEMP%\tmpfile

pushd %~dp0
setx /M CROWDIN_HOME "%cd%"
setx /M PATH "%PATH%;%cd%"
...
```

Otherwise we might be setting `PATH` and `CROWDIN_HOME` into totally wrong location, such as `C:\Windows\system32`, as there is no check that verifies if crowdin binary even exists in that location in the first place.

Thanks for considering this small enhancement. I'd send a PR but I don't see this file anywhere.

**Comment by ihor-popyk** [comment]
Hi @JustArchi 
Will upgrade script in the next version.
Thanks a lot!
