### ISSUE TITLE
Very slow on multiple files

### ISSUE THREAD

**Issue by STRML** [crowdin/crowdin-cli-2#62]
We have a project with about 140 translation files; we generate one per page and one per UI component.

Both the Ruby tool and this one are very slow for this use case. We see about 2-3 seconds per file which makes this part of our build take nearly 6 minutes, making it the slowest part of our build.

The older Ruby version took about 3 minutes, which is still slow but not so painful.

Could these be uploaded in parallel or pipelined as to not be so slow?

**Comment by STRML** [comment]
This made it much less painful: https://github.com/STRML/crowdin-cli/commit/1318b8a96ceff5dfcae5ad7e74e75c79919eb062

**Comment by grydstedt** [comment]
Will this be merged?

**Comment by STRML** [comment]
Happy to put forward a PR if there's any interest in merging it, but given I've gotten radio silence from CrowdIn for a while, I don't think that's likely.

**Comment by mamantoha** [comment]
Hi @STRML . Ruby version of `crowdin-cli` is unmaintained, but I would like to accept you PR with threads.

**Comment by STRML** [comment]
Please do. It is much faster than the python version when threaded.

**Comment by mamantoha** [comment]
@STRML version `0.7.0` uploaded to RubyGems.
Multiple threads dramatically increase uploading speed. Thanks.

**Comment by lifenautjoe** [comment]
Yes please!

**Comment by Venorcis** [comment]
We have around 40 files, and are experiencing the same issue where uploading is really slow, already taking 100% CPU even?

**Comment by andrii-bodnar** [comment]
Fixed in [CLI 3](https://github.com/crowdin/crowdin-cli-2/tree/cli3#readme) by implementing multithreading for files upload commands.
